name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
      - name: Test
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          command: test
