name: Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - "7.4"
          - "8.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          echo UID=`id -u` >> $GITHUB_ENV
          echo GID=`id -g` >> $GITHUB_ENV

      - name: Build
        run: docker-compose build
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Install
        run: docker-compose run romans composer install

      - name: Test
        run: docker-compose run -e COVERAGE_OPTIONS romans composer test
        env:
          COVERAGE_OPTIONS: --coverage-text --coverage-html build/coverage --coverage-clover build/coverage.xml

      - name: Archive Coverage
        uses: actions/upload-artifact@v2
        with:
          name: php-${{ matrix.php_version }}_coverage
          path: build/coverage/

      - name: Package
        run: docker-compose run romans composer archive --dir build --format zip --file package
        if: matrix.php_version == '8.0'

      - name: Package Artifact
        uses: actions/upload-artifact@v2
        if: matrix.php_version == '8.0'
        with:
          name: package
          path: build/package.zip

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -f build/coverage.xml
        if: github.ref == 'refs/heads/main' && matrix.php_version == '8.0'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean
        run: docker-compose down
        if: always()
