name: Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - "7.4"
          - "8.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          echo UID=`id -u` >> $GITHUB_ENV
          echo GID=`id -g` >> $GITHUB_ENV

      - name: Build
        run: docker-compose build
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Install
        run: docker-compose run romans composer install

      - name: Test
        run: docker-compose run -e COVERAGE_OPTIONS romans composer test
        env:
          COVERAGE_OPTIONS: --coverage-text --coverage-html build/coverage

      - name: Package
        run: docker-compose run romans composer archive --dir build --format zip --file package

      - name: Archive Coverage
        uses: actions/upload-artifact@v2
        with:
          name: php-${{ matrix.php_version }}_coverage
          path: build/coverage/

      - name: Archive Package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/package.zip

      - name: Clean
        run: docker-compose down
        if: ${{ always() }}
