name: Updated

on:
  push:
    branches: ["feature/updated"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - 7.4
          - 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          echo UID=`id -u` >> $GITHUB_ENV
          echo GID=`id -g` >> $GITHUB_ENV

      - name: Build
        run: docker-compose build
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Install
        run: docker-compose run romans composer install

      - name: Check Dependencies
        run: docker-compose run romans composer outdated

      - name: Check Dependencies Direct
        run: docker-compose run romans composer outdated --direct --strict

      - name: Update Dependencies
        run: docker-compose run romans composer update
        if: ${{ failure() }}

      - name: Test
        run: docker-compose run romans composer test
        if: ${{ failure() }}

      - name: Clean
        run: docker-compose down
        if: ${{ always() }}
